//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IELTSAppProject.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IELTSAppProject.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принять.
        /// </summary>
        internal static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить в подборку.
        /// </summary>
        internal static string addToCollection {
            get {
                return ResourceManager.GetString("addToCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл записи не найден, это ошибка, приносим свои извинения..
        /// </summary>
        internal static string answerFileMistake {
            get {
                return ResourceManager.GetString("answerFileMistake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ сохранён..
        /// </summary>
        internal static string answerIsSaved {
            get {
                return ResourceManager.GetString("answerIsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средний балл: .
        /// </summary>
        internal static string avargeScore {
            get {
                return ResourceManager.GetString("avargeScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверить всё.
        /// </summary>
        internal static string checkAll {
            get {
                return ResourceManager.GetString("checkAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Китайский.
        /// </summary>
        internal static string chiLanguage {
            get {
                return ResourceManager.GetString("chiLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите язык, на котором вы хотите работать в приложении.
        /// </summary>
        internal static string chooseCurrentLanguage {
            get {
                return ResourceManager.GetString("chooseCurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор языка.
        /// </summary>
        internal static string chooseLanguage {
            get {
                return ResourceManager.GetString("chooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите нужный режим.
        /// </summary>
        internal static string chooseModeTextBlock {
            get {
                return ResourceManager.GetString("chooseModeTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конвертировать в docx.
        /// </summary>
        internal static string convertBTN {
            get {
                return ResourceManager.GetString("convertBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string deleteCollection {
            get {
                return ResourceManager.GetString("deleteCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для начала работы советуем вам пройти входное тестирование, чтобы мы могли собрать статистику и вы увидели какие задания у вас получаются хуже. Если вы уже решали входной тест, можете продолжить  работу с нужными вам заданиями.
        /// </summary>
        internal static string describeTextBlockFirstTestPage {
            get {
                return ResourceManager.GetString("describeTextBlockFirstTestPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название новой персональной подборки:.
        /// </summary>
        internal static string dialogBoxMessage {
            get {
                return ResourceManager.GetString("dialogBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский.
        /// </summary>
        internal static string engLanguage {
            get {
                return ResourceManager.GetString("engLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите свой ответ сюда..
        /// </summary>
        internal static string EnterAnswerHere {
            get {
                return ResourceManager.GetString("EnterAnswerHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запишите свой ответ здесь:.
        /// </summary>
        internal static string EnterAnswerHereMessage {
            get {
                return ResourceManager.GetString("EnterAnswerHereMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Испанский.
        /// </summary>
        internal static string espLanguage {
            get {
                return ResourceManager.GetString("espLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статистика по сданным экзаменам:
        ///(Без учета Writing и Speaking).
        /// </summary>
        internal static string examsStatistics {
            get {
                return ResourceManager.GetString("examsStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У меня мало времени до экзамена!.
        /// </summary>
        internal static string fewTimeBeforeExam {
            get {
                return ResourceManager.GetString("fewTimeBeforeExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файлы с заданиями скачаны и находятся на вашем рабочем столе.
        /// </summary>
        internal static string fileInstalled {
            get {
                return ResourceManager.GetString("fileInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти задания для своих учеников.
        /// </summary>
        internal static string findForPupils {
            get {
                return ResourceManager.GetString("findForPupils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помощь.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Варианты экзамены IELTS.
        /// </summary>
        internal static string IELTSvariants {
            get {
                return ResourceManager.GetString("IELTSvariants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основной каталог заданий.
        /// </summary>
        internal static string mainCatalog {
            get {
                return ResourceManager.GetString("mainCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На главный экран.
        /// </summary>
        internal static string mainScreen {
            get {
                return ResourceManager.GetString("mainScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои подборки заданий.
        /// </summary>
        internal static string myCollections {
            get {
                return ResourceManager.GetString("myCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои ошибки.
        /// </summary>
        internal static string myMistakes {
            get {
                return ResourceManager.GetString("myMistakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Моя статистика.
        /// </summary>
        internal static string myStatistics {
            get {
                return ResourceManager.GetString("myStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здесь еще нет подходящих подборок.
        /// </summary>
        internal static string noNeededCollectionsYet {
            get {
                return ResourceManager.GetString("noNeededCollectionsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сейчас ничего не проигрывается..
        /// </summary>
        internal static string nothingIsPlaying {
            get {
                return ResourceManager.GetString("nothingIsPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работать по своему усмотрению (не решать входной вариант).
        /// </summary>
        internal static string notSolveEnterVariantBTN {
            get {
                return ResourceManager.GetString("notSolveEnterVariantBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество сданных экзаменов: .
        /// </summary>
        internal static string passedExamsQuantity {
            get {
                return ResourceManager.GetString("passedExamsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось открыть PDF с критериями..
        /// </summary>
        internal static string PDFmistake {
            get {
                return ResourceManager.GetString("PDFmistake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Играть пример на макс. балл.
        /// </summary>
        internal static string playIdealAnswer {
            get {
                return ResourceManager.GetString("playIdealAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Воспроизведение остановлено..
        /// </summary>
        internal static string playingWasStopped {
            get {
                return ResourceManager.GetString("playingWasStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Играть/Пауза.
        /// </summary>
        internal static string playOrPause {
            get {
                return ResourceManager.GetString("playOrPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Играть свою запись.
        /// </summary>
        internal static string playUserAnswer {
            get {
                return ResourceManager.GetString("playUserAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться назад.
        /// </summary>
        internal static string prevPage {
            get {
                return ResourceManager.GetString("prevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рекомендованное время:.
        /// </summary>
        internal static string recomendedTime {
            get {
                return ResourceManager.GetString("recomendedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рекомендуется поработать над:.
        /// </summary>
        internal static string recommendToWorkOn {
            get {
                return ResourceManager.GetString("recommendToWorkOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала запишите свой ответ..
        /// </summary>
        internal static string recordAnswerFirst {
            get {
                return ResourceManager.GetString("recordAnswerFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись можно проиграть после добавления ответа..
        /// </summary>
        internal static string recordingEnableOnlyAfterSettingAnswer {
            get {
                return ResourceManager.GetString("recordingEnableOnlyAfterSettingAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись идёт..
        /// </summary>
        internal static string recordingInProgress {
            get {
                return ResourceManager.GetString("recordingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись ещё не начата..
        /// </summary>
        internal static string recordingNotStartedMessage {
            get {
                return ResourceManager.GetString("recordingNotStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        internal static string refuse {
            get {
                return ResourceManager.GetString("refuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перед написанием эссе не забудте выбрать тему выше.
        /// </summary>
        internal static string remindToChooseTopic {
            get {
                return ResourceManager.GetString("remindToChooseTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перед данным действием необходимо выбрать тему.
        /// </summary>
        internal static string remindToChooseTopicMessageBox {
            get {
                return ResourceManager.GetString("remindToChooseTopicMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат и пример на макс. балл:.
        /// </summary>
        internal static string ResAndMaxPointsMessage {
            get {
                return ResourceManager.GetString("ResAndMaxPointsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        internal static string rusLanguage {
            get {
                return ResourceManager.GetString("rusLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить ответ.
        /// </summary>
        internal static string saveAnswer {
            get {
                return ResourceManager.GetString("saveAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить выбор темы.
        /// </summary>
        internal static string saveTopicChoice {
            get {
                return ResourceManager.GetString("saveTopicChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотреть критерии оценивания.
        /// </summary>
        internal static string SeeEvaluationCriteria {
            get {
                return ResourceManager.GetString("SeeEvaluationCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Самопроверка.
        /// </summary>
        internal static string selfCheck {
            get {
                return ResourceManager.GetString("selfCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотр эссе можно будет выполнять только после сохранения собственного.
        /// </summary>
        internal static string showEnableOnlyAfterAnswering {
            get {
                return ResourceManager.GetString("showEnableOnlyAfterAnswering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смотреть эссе на макс..
        /// </summary>
        internal static string showMaxEssay {
            get {
                return ResourceManager.GetString("showMaxEssay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смотреть своё эссе.
        /// </summary>
        internal static string showUserEssay {
            get {
                return ResourceManager.GetString("showUserEssay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Решать входной вариант.
        /// </summary>
        internal static string solveEnterVariantBTN {
            get {
                return ResourceManager.GetString("solveEnterVariantBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Решать готовые варианты в формате IELTS.
        /// </summary>
        internal static string solveIELTSformat {
            get {
                return ResourceManager.GetString("solveIELTSformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать (продолжить) подготовку.
        /// </summary>
        internal static string startOrContinuePreporation {
            get {
                return ResourceManager.GetString("startOrContinuePreporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись.
        /// </summary>
        internal static string startRecording {
            get {
                return ResourceManager.GetString("startRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоп.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задания по разделам (Listening, Reading, Speaking, Writing).
        /// </summary>
        internal static string tasksByType {
            get {
                return ResourceManager.GetString("tasksByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество успешно/неуспешно.
        /// </summary>
        internal static string tasksStatisicsPart1 {
            get {
                return ResourceManager.GetString("tasksStatisicsPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выполненных заданий по категориям:.
        /// </summary>
        internal static string tasksStatisicsPart2 {
            get {
                return ResourceManager.GetString("tasksStatisicsPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вид заданий:.
        /// </summary>
        internal static string taskType {
            get {
                return ResourceManager.GetString("taskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виды заданий.
        /// </summary>
        internal static string taskTypes {
            get {
                return ResourceManager.GetString("taskTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Можно слушать свой и пример идеального варианты ответа..
        /// </summary>
        internal static string UserAndIdealAnswersAreEnable {
            get {
                return ResourceManager.GetString("UserAndIdealAnswersAreEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не выбрали тему!.
        /// </summary>
        internal static string UserDidNotChooseTopic {
            get {
                return ResourceManager.GetString("UserDidNotChooseTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название подборки:.
        /// </summary>
        internal static string variantName {
            get {
                return ResourceManager.GetString("variantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать в приложение для подготовки к экзамену в формате IELTS.
        /// </summary>
        internal static string welcomeTextBlock {
            get {
                return ResourceManager.GetString("welcomeTextBlock", resourceCulture);
            }
        }
    }
}
