//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IELTSAppProject.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IELTSAppProject.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить в подборку.
        /// </summary>
        internal static string addToCollection {
            get {
                return ResourceManager.GetString("addToCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверить всё.
        /// </summary>
        internal static string checkAll {
            get {
                return ResourceManager.GetString("checkAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Китайский.
        /// </summary>
        internal static string chiLanguage {
            get {
                return ResourceManager.GetString("chiLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите язык, на котором вы хотите работать в приложении.
        /// </summary>
        internal static string chooseCurrentLanguage {
            get {
                return ResourceManager.GetString("chooseCurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор языка.
        /// </summary>
        internal static string chooseLanguage {
            get {
                return ResourceManager.GetString("chooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите нужный режим.
        /// </summary>
        internal static string chooseModeTextBlock {
            get {
                return ResourceManager.GetString("chooseModeTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конвертировать в docx.
        /// </summary>
        internal static string convertBTN {
            get {
                return ResourceManager.GetString("convertBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для начала работы советуем вам пройти входное тестирование, чтобы мы могли собрать статистику и вы увидели какие задания у вас получаются хуже. Если вы уже решали входной тест, можете продолжить  работу с нужными вам заданиями.
        /// </summary>
        internal static string describeTextBlockFirstTestPage {
            get {
                return ResourceManager.GetString("describeTextBlockFirstTestPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский.
        /// </summary>
        internal static string engLanguage {
            get {
                return ResourceManager.GetString("engLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Испанский.
        /// </summary>
        internal static string espLanguage {
            get {
                return ResourceManager.GetString("espLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У меня мало времени до экзамена!.
        /// </summary>
        internal static string fewTimeBeforeExam {
            get {
                return ResourceManager.GetString("fewTimeBeforeExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти задания для своих учеников.
        /// </summary>
        internal static string findForPupils {
            get {
                return ResourceManager.GetString("findForPupils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помощь.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Варианты экзамены IELTS.
        /// </summary>
        internal static string IELTSvariants {
            get {
                return ResourceManager.GetString("IELTSvariants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои подборки заданий.
        /// </summary>
        internal static string myCollections {
            get {
                return ResourceManager.GetString("myCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои ошибки.
        /// </summary>
        internal static string myMistakes {
            get {
                return ResourceManager.GetString("myMistakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Моя статистика.
        /// </summary>
        internal static string myStatistics {
            get {
                return ResourceManager.GetString("myStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работать по своему усмотрению (не решать входной вариант).
        /// </summary>
        internal static string notSolveEnterVariantBTN {
            get {
                return ResourceManager.GetString("notSolveEnterVariantBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Играть/Пауза.
        /// </summary>
        internal static string playOrPause {
            get {
                return ResourceManager.GetString("playOrPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться назад.
        /// </summary>
        internal static string prevPage {
            get {
                return ResourceManager.GetString("prevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рекомендованное время:.
        /// </summary>
        internal static string recomendedTime {
            get {
                return ResourceManager.GetString("recomendedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        internal static string rusLanguage {
            get {
                return ResourceManager.GetString("rusLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Решать входной вариант.
        /// </summary>
        internal static string solveEnterVariantBTN {
            get {
                return ResourceManager.GetString("solveEnterVariantBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Решать готовые варианты в формате IELTS.
        /// </summary>
        internal static string solveIELTSformat {
            get {
                return ResourceManager.GetString("solveIELTSformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать (продолжить) подготовку.
        /// </summary>
        internal static string startOrContinuePreporation {
            get {
                return ResourceManager.GetString("startOrContinuePreporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задания по разделам (Listening, Reading, Speaking, Writing).
        /// </summary>
        internal static string tasksByType {
            get {
                return ResourceManager.GetString("tasksByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вид заданий:.
        /// </summary>
        internal static string taskType {
            get {
                return ResourceManager.GetString("taskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать в приложение для подготовки к экзамену в формате IELTS.
        /// </summary>
        internal static string welcomeTextBlock {
            get {
                return ResourceManager.GetString("welcomeTextBlock", resourceCulture);
            }
        }
    }
}
